### ISSUE TITLE
How exactly does the Precipitation computation work?

### ISSUE THREAD

**Issue by JPManicar** [iconsumeplutonium/procedural-biome-generation#1]
I'd like to ask, I tried implementing the precipitation script to my project and is a bit curious on how does it work. My precipitation map returns values between 1 - 90(?) or maybe 100. I was just curious on why is the max and min precipitation values on the biomes are between 0 -1 but the values in the 2d array is not between 0 -1. Is there something wrong with the way I implemented it in my project or is that really how it works? 

 I didn't know how or where to contact you to ask so I just put it here. Thanks in advance.

**Comment by iconsumeplutonium** [comment]
My best guess would be that your precipitation function is only calculating humidity (which should be between between 1 to 100 or so). In line 100 of [MapUtilities.cs](https://github.com/iconsumeplutonium/procedural-biome-generation/blob/main/Procedural%20Biome%20Generation/Assets/MapUtilities.cs), GeneratePrecipitationMap() makes a call to CalculatePrecipitation() at the end, which takes humidity and temperature and returns a precipitation value between 0 and 1. Hopefully that fixes your issue.
